[pyprland]
plugins = ["scratchpads"]

[scratchpads.defaults]
excludes = "*"
restore_excluded = false
lazy = false
alt_toggle = true
multi = false

[scratchpads.pavucontrol]
use = "defaults"
command = "pavucontrol"
size = "60% 40%"
position = "20% 30%"
class = "org.pulseaudio.pavucontrol"

[scratchpads.blueman-manager]
use = "defaults"
command = "blueman-manager"
size = "60% 40%"
position = "20% 30%"
class = "blueman-manager"

[scratchpads.qalculate]
use = "defaults"
command = "qalculate-gtk"
size = "40% 40%"
position = "30% 30%"
class = "qalculate-gtk"
