[pyprland]
plugins = ["scratchpads"]

[scratchpads.pavucontrol]
command = "pavucontrol"
size = "60% 40%"
position = "20% 30%"
class = "org.pulseaudio.pavucontrol"
lazy = "false"

[scratchpads.blueman-manager]
command = "blueman-manager"
size = "60% 40%"
position = "20% 30%"
class = "blueman-manager"
lazy = "false"

[scratchpads.qalculate]
command = "qalculate-gtk"
size = "40% 40%"
position = "30% 30%"
class = "qalculate-gtk"
lazy = "false"

[scratchpads.tk]
command = "npm --prefix ~/.local/share/tk-workspace start"
size = "100% 100%"
position = "0% 0%"
match_by = "title"
title = "tk-workspace-browser"
unfocus = "hide"
lazy = "false"

[scratchpads.bitwarden]
command = "bitwarden"
size = "50% 50%"
position = "25% 25%"
class = "Bitwarden"
lazy = "false"
